rjmurillo/moq.analyzers

- README.md
- Source/Moq.Analyzers.Test/Data/SetupOnlyForOverridableMembers.cs
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers.Test/SetupShouldBeUsedOnlyForOverridableMembersAnalyzerTests.ShouldPassIfGoodParameters.approved.txt
- Source/Moq.Analyzers.Test/SetupShouldBeUsedOnlyForOverridableMembersAnalyzerTests.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/Diagnostics.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
This implementation handles only `Setup()` for methods. The case with properties is currently ignored because is much more complex, especially that `Moq` supports recursive mocking for properties. I've set the default severity level for `ERROR` because it always fails in runtime.
> Added analyzer that verify if method provider for Setup() is overridable

- README.md
- Source/Moq.Analyzers.Test/AsAcceptOnlyInterfaceAnalyzerTests.ShouldPassIfGoodParameters.approved.txt
- Source/Moq.Analyzers.Test/AsAcceptOnlyInterfaceAnalyzerTests.cs
- Source/Moq.Analyzers.Test/Data/AsAcceptOnlyInterface.cs
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/Diagnostics.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/MoqMethodDescriptor.cs
I've added an analyzer that verifies if the type parameter accepted by Moq.As represents an interface.
> New feature: Mock.As() should take interfaces only

- Source/Moq.Analyzers.Test/Data/SetupShouldNotIncludeAsyncResult.cs
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers.Test/SetupShouldNotIncludeAsyncResultAnalyzerTests.ShouldPassIfSetupProperly.approved.txt
- Source/Moq.Analyzers.Test/SetupShouldNotIncludeAsyncResultAnalyzerTests.cs
- Source/Moq.Analyzers/Diagnostics.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
When using the result of an async operation (returning generic Task<>), rule 1200 fires indicating setup should only be used for overridable members. This is technically true because Task<> is abstract, however, the message is not helpful/actionable by a developer.
Added new rule, `Moq1201`, that is triggered when the setup method is for a Task and that Task includes the `.Result`. The error reflects the guidance from Moq, which is to use the `.ReturnsAsync` method for setup.
Resolves #4
> Added async result check as rule 1201

- README.md
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Addition of documentation for rule 1201 added in #5
- Correction of markdown lint issues in root README.md file
- Move test project forward to minimum supported version of .NET Core (3.1, supported until Dec of 2022)
> Additional updates for upcoming release

- .github/workflows/codeql.yml
This change introduces a new GitHub action with the CodeQL scanner using the security-extended rule set. For more information, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs
> Create codeql.yml to analyze C# code

- Source/Moq.Analyzers/Moq.Analyzers.csproj
The `TargetFramework` in the `Moq.Analyzers.csproj` file has been updated from `netstandard1.3` to `netstandard2.0`, indicating that the project now targets the .NET Standard 2.0 framework.
Resolves #11
> Update TargetFramework to NET Standard 2.0

- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- global.json
Create a basic GitHub actions pipeline for build / test. I've commented out code relating to making NuGet packages build artifacts, and commented out the NuGet publish step from the release pipeline. Those are tracked via issues.
I also added a `global.json` so that the actions runner uses a consistent version of the dotnet SDK.
Fixes #10.
> Create a basic GitHub Actions pipeline

- .github/workflows/main.yml
- .github/workflows/pr.yml
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
Copy/paste error on my part. The default branch is `master` but I used `main`. Wasn't able to test until the pipelines were merged.
In order to verify the tests pass I also needed to:
1. Upgrade the tests from the unsupported `netcoreapp3.1` to `net6.0`.
2. Disable uploading the test report until #22 is fixed
Verified they run now:
> Fix GitHub actions branch 'main' -> 'master'

- .github/workflows/main.yml
- Directory.Build.props
- Directory.Build.targets
- build/targets/artifacts/Artifacts.props
- build/targets/artifacts/Artifacts.targets
- build/targets/tests/Tests.props
- build/targets/tests/Tests.targets
Fixes #22.
- Add `Directory.Build.props` and `.targets` for build customization
- Enable .NET 8 SDK's simplified artifacts output feature
- Enable TRX files in VSTest
- Update CI pipeline to publish `.trx` files as artifacts
> Use .NET 8 SDK's artifacts output and enable test reports in CI

- .github/workflows/main.yml
When using Verify, when there is a failure upload the *.received.* files for comparison (in case of LF or BOM differences, not just contents).
> Update main.yml to upload .received on failure

- Source/Moq.Analyzers.Test/ModuleInitializer.cs
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers.Test/PackageTests.Baseline#contents.verified.txt
- Source/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
- Source/Moq.Analyzers.Test/PackageTests.cs
Add a test that inspects the `.nupkg` created as part of the build (via `<GeneratePackageOnBuild>`) and dumps the manifest and file structure to prevent accidental regressions in the package format.
> Add .nupkg baseline with Verify

- Source/Moq.Analyzers.Test/PackageTests.Baseline#contents.verified.txt
- Source/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
- Source/Moq.Analyzers/Moq.Analyzers.csproj
Contributes to #31 (more fixes needed)
This brings our NuGet package closer to best practices:
- Swaps the license URL for an expression. This makes automated compliance easier for users
- Add our README to the package so it shows up on NuGet.org
- Mark the package as a development dependency so it doesn't show up as a dependency if users' packages
> Set package README, license expression, and development dependency

- .github/workflows/main.yml
- Directory.Build.props
- Directory.Build.targets
- Directory.Packages.props
- Source/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
- Source/Moq.Analyzers/Moq.Analyzers.csproj
- build/targets/reproducible/Packages.props
- build/targets/reproducible/Reproducible.props
- build/targets/reproducible/Reproducible.targets
- global.json
Contributes to #31 (more fixes needed).
This enables "reproducible builds" for the NuGet package:
- Ensure `Deterministic`
- Enable SourceLink
- Embed debug symbols
> Follow reproducible builds best practices for package

- Source/Moq.Analyzers.Test/PackageTests.Baseline#contents.verified.txt
- Source/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
- Source/Moq.Analyzers/Moq.Analyzers.csproj
Fixes #31.
Address two related issues:
1. Don't pack the analyzer in the `lib/` folder, as that makes it an input to the user's compilation
2. Because there is no lib, suppress the dependency on .NET Standard 2.0, as that's an implementation detail of the analyzer and not a requirement of the package.
To do that I also removed the `<NoPackageAnalysis>`, which disables all package analysis, and instead fixed the raised issues via `<IncludeBuildOutput>` and `<SuppressDependenciesWhenPacking>`.
> Remove package dependencies and don't publish analyzer as a lib

- Source/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
- Source/Moq.Analyzers/Moq.Analyzers.csproj
- Conform to value in LICENSE file
- Update Nuget package metadata
- Update Nuspec baseline
Fixes #46 and fixes #47
> Update Moq.Analyzers.csproj NuGet package metadata

- .github/workflows/release.yml
Failed with error
```
The workflow is not valid. .github/workflows/release.yml (Line: 15, Col: 3): Error calling workflow 'Litee/moq.analyzers/.github/workflows/main.yml@3f7a811a4ef5e55ed118b196f755257f9c334ac9'. The workflow is requesting 'packages: read, security-events: write', but is only allowed 'packages: none, security-events: none'.
```
> Update release.yml permissions

- .editorconfig
- Directory.Packages.props
- Source/Moq.Analyzers.Test/Helpers/CodeFixVerifier.cs
- Source/Moq.Analyzers.Test/Helpers/DiagnosticVerifier.Helper.cs
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/Moq.Analyzers.csproj
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
- build/targets/compiler/Compiler.props
Most often this was while getting the type information from the semantic model. In cases where the asynchronous operation is cancelled, the underlying calls would not be aborted because we did not propagate forward the cancellation token. This was not picked up by analyzer CA2016 because the cancellation token is not provided on the method used by `DiagnosticAnalyzer`, but rather on the `SyntaxNodeAnalysisContext` instance passed in. 
The issue was corrected by adding a new analyzer package and enabling an analyzer rule within that package. Both rules are set to error in `.editorconfig` to avoid introducing new code with this issue
Fixes #43
> Add cancellation tokens to methods that have a parameter but we don't pass

- Directory.Build.props
- Directory.Build.targets
- Directory.Packages.props
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers/Moq.Analyzers.csproj
- build/targets/codeanalysis/CodeAnalysis.props
- build/targets/codeanalysis/CodeAnalysis.targets
- build/targets/codeanalysis/Packages.props
- build/targets/compiler/Compiler.props
This is a preparatory refactoring change for the test updates.
1. Move code analysis build settings from the `compiler` slice to its own `codeanalysis` slice
2. Update `Microsoft.CodeAnalysis.Analyzers`, `Roslynator.Analyzers`, and `StyleCop.Analyzers` to their latest versions
3. Fix some duplicate definitions between the slices and the projects
4. Move `Microsoft.CodeAnalysis.CSharp.Workspaces` out of the code analysis slice because it's part of the analyzer's public API and not a private code analyzer
> Extract code analysis to its own build slice and update analyzers to latest versions

- Directory.Packages.props
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- build/targets/tests/Packages.props
- build/targets/tests/Tests.props
Another preparatory refactoring change for the test changes.
1. Move PackageVersions for test packages to the build slice
2. Move PackageReferences for test packages to the build slice
3. Update to latest versions of test packages
4. Enable parallel xUnit tests
> Move test packages to build slice, update to latest version, and enable parallel tests

- README.md
- Source/Moq.Analyzers.Test/Helpers/AnalyzerTestExtensions.cs
- Source/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
- Source/Moq.Analyzers/Moq.Analyzers.csproj
After transfer of ownership, URLs needed to be updated in a few places:
- README.md
- Comments in code
- Moq.Analyzers.csproj for NuGet package
- Verified NuSpec
Fixes #67
> Updated references from Litee to rjmurillo

- Source/Moq.Analyzers.Test/AbstractClassTests.cs
- Source/Moq.Analyzers.Test/AsAcceptOnlyInterfaceAnalyzerTests.cs
- Source/Moq.Analyzers.Test/CallbackSignatureShouldMatchMockedMethodCodeFixTests.cs
- Source/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.cs
- Source/Moq.Analyzers.Test/GlobalUsings.cs
- Source/Moq.Analyzers.Test/Helpers/DiagnosticVerifier.cs
- Source/Moq.Analyzers.Test/ModuleInitializer.cs
- Source/Moq.Analyzers.Test/NoConstructorArgumentsForInterfaceMockAnalyzerTests.cs
- Source/Moq.Analyzers.Test/NoMethodsInPropertySetupAnalyzerTests.cs
- Source/Moq.Analyzers.Test/NoSealedClassMocksAnalyzerTests.cs
- Source/Moq.Analyzers.Test/PackageTests.cs
- Source/Moq.Analyzers.Test/SetupShouldBeUsedOnlyForOverridableMembersAnalyzerTests.cs
- Source/Moq.Analyzers.Test/SetupShouldNotIncludeAsyncResultAnalyzerTests.cs
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/GlobalUsings.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/MoqMethodDescriptor.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
Clean up of using statements
- Remove using directives that are unused
- Convert using directives to global usings that are used by >50% of files
Fixes #62
> Clean up of using statements

- Source/Moq.Analyzers.Test/Helpers/AnalyzerTestExtensions.cs
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
Two simple and related performance improvements:
1. Enable concurrent execution of the analyzer. Verified via manual code inspection + tests that there's no state to maintain between invocations
2. Disable the analyzer in generate code contexts. Things like Razor and Entity Framework can generate large volumes of code that the user isn't directly responsible for.
> Enable ConcurrentExecution and disable generated code analysis

- Source/Moq.Analyzers.Test/Helpers/AnalyzerTestExtensions.cs
- Source/Moq.Analyzers.Test/Helpers/ReferenceAssemblyCatalog.cs
The testing framework does a bunch of heavy lifting to resolve references for set of `ReferenceAssemblies`, including potentially running the NuGet client to download packages. This class caches the ReferenceAssemblies class (which is thread-safe), so that package resolution only happens once for a given configuration.
The is the same approach taken by https://github.com/dotnet/roslyn-analyzers/blob/4d5fd9da36d64d4c3370b8813122e226844fc6ed/src/Test.Utilities/AdditionalMetadataReferences.cs.
This cuts test time from ~40 seconds to ~20 seconds on my machine.
> Cache reference assemblies between tests to improve performance

- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/Diagnostics.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/Moq.Analyzers.csproj
- Source/Moq.Analyzers/MoqMethodDescriptor.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
This reduces the backlog of warnings by about half, removing many cases for passing null references to methods and null dereference. The remaining warnings are from multiple sources: TODO, diagnostic best practices, and some tricker items we'll need to look at
Related to #26
> Update code to remove warnings from backlog

- .editorconfig
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/MoqMethodDescriptor.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
There is mixed use of explicit types and var keyword. There are also cases where the var keyword cannot be used. Rather than have mixed cases, update all code to use explicit types and enable .editorconfig rule to enforce code style
Fixes #53
> Convert from var to explicit type

- CODE-OF-CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/rules/Moq1000.md
- docs/rules/Moq1001.md
- docs/rules/Moq1002.md
- docs/rules/Moq1100.md
- docs/rules/Moq1101.md
- docs/rules/Moq1200.md
- docs/rules/Moq1201.md
- docs/rules/Moq1300.md
- docs/rules/README.md
Made a pass at the README and other docs to make the project easier to use.
- Moved the code of conduct out of README into `CODE-OF-CONDUCT.md` so that GitHub can pick it up automatically and add it to the UI
- Move the contributing docs out of README and into `CONTRIBUTING.md` so that GitHub can pick it up automatically and add it to the UI
- Add NuGet and build badges to README, for #15
- Small copy edits to README
- Added a `//docs/rules/` folder and added a doc per rule with an explanation and sample
> Clean up README and add docs for each analyzer rule

- build/targets/tests/Tests.targets
#79 added code coverage reports, but broke a basic `dotnet test`. In that case no Cobertura reports are generated and thus the `<ReportGenerator>` task fails.
Fix by conditioning the report generator on having reports to process.
> Fix `dotnet test` when not generating code coverage reports

- Source/Moq.Analyzers.Test/AsAcceptOnlyInterfaceAnalyzerTests.cs
- Source/Moq.Analyzers.Test/CallbackSignatureShouldMatchMockedMethodCodeFixTests.cs
- Source/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.cs
- Source/Moq.Analyzers.Test/Helpers/AnalyzerVerifier.cs
- Source/Moq.Analyzers.Test/Helpers/CodeFixVerifier.cs
- Source/Moq.Analyzers.Test/Helpers/ReferenceAssemblyCatalog.cs
- Source/Moq.Analyzers.Test/Helpers/Test.cs
- Source/Moq.Analyzers.Test/Helpers/TestDataExtensions.cs
- Source/Moq.Analyzers.Test/NoConstructorArgumentsForInterfaceMockAnalyzerTests.cs
- Source/Moq.Analyzers.Test/NoMethodsInPropertySetupAnalyzerTests.cs
- Source/Moq.Analyzers.Test/NoSealedClassMocksAnalyzerTests.cs
- Source/Moq.Analyzers.Test/SetupShouldBeUsedOnlyForOverridableMembersAnalyzerTests.cs
- Source/Moq.Analyzers.Test/SetupShouldNotIncludeAsyncResultAnalyzerTests.cs
Refactor test cases so that they test with an "old" version of Moq (4.8.2) and now also a "new" version of Moq (4.18.4).
Fixes #58 
4.8.2 was the pre-existing test version. Any version prior to 4.13.1 works. (4.13.1 changed the internal implementation of `.As<T>()` [see https://github.com/devlooped/moq/commit/b552aeddd82090ee0f4743a1ab70a16f3e6d2d11]).
4.18.4 is the most downloaded version of Moq.
> Refactor test cases to matrix on Moq version

- Source/Moq.Analyzers/AnalyzerReleases.Shipped.md
- Source/Moq.Analyzers/AnalyzerReleases.Unshipped.md
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
Enable analyzer release tracking (i.e. `AnalyzerReleases.Shipped.md`). Fixes #72.
Wokflow was as follows:
1. Download old release from NuGet
2. Open in ILSpy to view the analyzer metadata
3. Create appropriate release in `AnalyzerReleases.Shipped.md`
4. GOTO 1
5. Add help links pointing to our `//docs/rules` files
- I tried to make the base URL a helper function, but the analyzer is unable to add documentation URLs to the Unshipped file if the URL isn't a constant. So instead I used string interpolation so at least the ID isn't repeated.
6. Use release analyzer codefix to add an unshipped section that adds help links
> Add analyzer release tracking

- Source/Moq.Analyzers.Test/.editorconfig
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
- build/targets/codeanalysis/CodeAnalysis.props
Fix SA0001: XML comment analysis is disabled due to project configuration
Added xmldocs for all of our public types in the analyzer project. Added a `.editorconfig` in the test project the demotes the various "xmldocs missing on public types" diagnostics from warnings to info/suggestions.
This contributes to #26 (more work needed).
> Fix SA0001: XML comment analysis is disabled due to project configuration

- .editorconfig
- Source/Moq.Analyzers.Test/AsAcceptOnlyInterfaceAnalyzerTests.cs
- Source/Moq.Analyzers.Test/GlobalSuppressions.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/GlobalSuppressions.cs
Contributes to #26 (more work needed).
Fix trivial cases of warnings and move some duplicated analyzer settings from `GlobalSupressions.cs` to `.editorconfig`.
> Fix trivial warnings

- .github/workflows/main.yml
- README.md
Updates to build to enable integration with Codacy
- Rename "Publish coverage summary" to "Publish coverage summary to GitHub" when posting SummaryGithub.md
- Add new step to upload Cobertura code coverage information to Codacy
- Add Codacy coverage and grade badges to README.md
> Update main.yml to add codacy test coverage

- .editorconfig
- Source/Moq.Analyzers.Test/.editorconfig
- Source/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.cs
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers.Test/PackageTests.cs
- Source/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/MoqAsMethodDescriptor.cs
- Source/Moq.Analyzers/MoqSetupMethodDescriptor.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- Source/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- Source/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- Source/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
- build/targets/codeanalysis/CodeAnalysis.props
- build/targets/codeanalysis/Packages.props
- build/targets/tests/Packages.props
- build/targets/tests/Tests.props
Several changes:
1. Add several new analyzers to check for code correctness and style
- [Sonar](https://www.nuget.org/packages/SonarAnalyzer.CSharp)
- [Multithreading](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers)
- [C# Guidelines](https://www.nuget.org/packages/CSharpGuidelinesAnalyzer)
- [Exhaustive matching](https://www.nuget.org/packages/ExhaustiveMatching.Analyzer)
2. Added suppressions for some of the new rules as they'll need more extensive refactoring to satisfy (e.g., methods have multiple responsibilities, there's too much coupling, poor encapsulation, etc.). Tracked in #90
3. Bump Meziantou.Analyzer to 2.0.157
> Add more analyzers and bump Meziantou.Analzer to latest version

- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- build/targets/tests/Packages.props
Remove `Microsoft.CodeAnalysis.CSharp.Analyzer.Testing` because it is duplicative with `Microsoft.CodeAnalysis.CSharp.CodeFix.Testing`. This is common when building analyzers that contain code fixes. From a testing perspective, an analyzer test is just a code fix test with an "empty" or "null pattern" code fixer.
This also unblocks #97, as the two packages otherwise need upgrading together. However, cleaning up our dependencies is preferred to creating a group in dependabot.
> Remove Microsoft.CodeAnalysis.CSharp.Analyzer.Testing

- .github/dependabot.yml
Add ignores in `dependabot.yml` for the few packages that can impact compatibility for our users.
> Dependabot ignore packages that impact customer compatibility

- .editorconfig
- Source/Moq.Analyzers.Test/CallbackSignatureShouldMatchMockedMethodCodeFixTests.cs
- Source/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.cs
- Source/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- Source/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- Source/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- Source/Moq.Analyzers/Helpers.cs
- Source/Moq.Analyzers/NoConstructorArgumentsForInterfaceMockAnalyzer.cs
- build/targets/codeanalysis/CodeAnalysis.props
- Updated `.editorconfig` to set policy on some duplicate warnings for TODO. Borrowed from #89 to make merging easier
- Updated cases where nullability was incorrect (something could be passed as null but wasn't, something was marked as nullable but wasn't). Where possible added asserts so we can catch cases when they arise.
- Removed `<NoWarn>` from `Moq.Analyzers.csproj`
- Added `<TreatWarningsAsErrors>` and `MSBuildTreatWarningsAsErrors` elements to `CodeAnalysis.props`
- Set each to `true` when MSBuild property `$(ContinuousIntegrationBuild)` is `true` from `DotNet.ReproducibleBuilds` package
> Enable warnings as errors

- .github/labeler.yml
- .github/workflows/label-issues.yml
- .github/workflows/label-pr.yml
Add automatic labeling for issues and PRs to cut down on administrative work. Will allow for more consistent reporting, especially when generating patch notes from PRs.
> Add auto labelers for Issues and PRs

- tests/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.cs
This is comprehensive and did not change the code coverage numbers.
Resolves #123
There are still blocks that are not covered:
https://github.com/rjmurillo/moq.analyzers/blob/e3e5dec23cf7660fc531006755cff62748d3c22b/src/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs#L208-L213
The `return null` cases
https://github.com/rjmurillo/moq.analyzers/blob/e3e5dec23cf7660fc531006755cff62748d3c22b/src/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs#L166-L175
> Update ConstructorArgumentsShouldMatchAnalyzer test cases to make sure all positive and negative cases are covered

- tests/Moq.Analyzers.Test/CompositeAnalyzer.cs
- tests/Moq.Analyzers.Test/Moq.Analyzers.Test.csproj
Adds new type `CompositeAnalyzer` that inherits from `DiagnosticAnalyzer`. This new analyzer uses reflection to load all types in the `Moq.Analyzers` assembly that derive from `DiagnosticAnalyzer`, are not abstract, and are classes.
The intended use is for diagnostic purposes
```csharp
using Verifier = Moq.Analyzers.Test.Helpers.AnalyzerVerifier<Moq.Analyzers.Test.CompositeAnalyzer>;
namespace Moq.Analyzers.Test;
public class FooAnalyzerTests
{
public static IEnumerable<object[]> TestData()
{
return new object[][]
{
["""new Mock<TestClass>(MockBehavior.Strict).Object.TaskAsync();"""],
}.WithNamespaces().WithReferenceAssemblyGroups();
}
[Theory]
[MemberData(nameof(TestData))]
public async Task Bar(string referenceAssemblyGroup, string @namespace, string mock)
{
await …
```
> Add composite analyzer to test all analyzers

- build/targets/reproducible/Packages.props
- build/targets/reproducible/Reproducible.targets
- build/targets/tests/Packages.props
- global.json
- tests/Moq.Analyzers.Test/PackageTests.Baseline#manifest.verified.nuspec
Update to the latest version of `DotNet.ReproducibleBuilds`. Doing so exposes a difference in how SourceLink is invoked between local and CI scenarios. I make local build work like CI by adding a RepositoryBranch if one isn't supplied (bug filed against the SourceLink repo to do the fallback directly). This then requires pulling in a newer version of `Verify.Nupkg` in order to scrub the new `branch` attribute.
> Update to latest version of DotNet.ReproducibleBuilds

- version.json
Milestone 0.1.1 has closed, we're on to 0.2.0
> Update version.json to 0.2.0

- build/targets/codeanalysis/CodeAnalysis.props
- build/targets/codeanalysis/CodeAnalysis.targets
- src/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- src/tools/PerfDiff/Logging/SimpleConsoleLogger.cs
- tests/.editorconfig
- tests/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.DefaultParam.cs
- tests/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.Delegates.cs
#91 intended to enable warnings as errors in CI. However, `$(ContinuousIntegrationBuild)` is set by `DotNet.ReproducibleBuilds`, and that package's .props file is imported _after_ our own Directory.Build.props. As a result, the properties were evaluated before they were set.
This change moves them into the .targets file as "computed properties" in order for them to pick up the configuration from .props files. This aligns with the [documented guidance](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#choose-between-adding-properties-to-a-props-or-targets-file) "Set dependent properties in .targets files, because they pick up customizations from individual projects.". I've also filed https://github.com/dotnet/reproducible-builds/issues/45 to see if we …
> Enable TreatWarningsAsErrors

- global.json
Update .NET SDK to the latest released version and disable `rollForward`.
Updates to the .NET SDK feature band can introduce new / updated analyzers (for instance, 8.0.400 adds [IDE0320](https://github.com/dotnet/roslyn/pull/73012)). As a result, updating the feature band isn't "safe" to do from a build reproducibility perspective. It will also conflict with #166.
That means the roll forward options available to us are:
- `patch`
- `latestPatch`
- `disable`
However, GitHub Actions don't support these options (tracked by https://github.com/actions/setup-dotnet/issues/448). Thus, the only `rollForward` strategy that currently does the same thing locally and in CI is `disabled`.
Once 448 is fixed, we can / should probably switch to `latestPatch` (tracked by #171).
This 'gotcha' is also added …
> Disable rollForward for SDK in global.json

- .config/dotnet-tools.json
- .github/workflows/main.yml
- CONTRIBUTING.md
- build/targets/codeanalysis/CodeAnalysis.props
- build/targets/codeanalysis/CodeAnalysis.targets
- build/targets/codeanalysis/Packages.props
- src/Moq.Analyzers/SquiggleCop.Baseline.yaml
- src/tools/PerfDiff/SquiggleCop.Baseline.yaml
- tests/Moq.Analyzers.Benchmarks/SquiggleCop.Baseline.yaml
- tests/Moq.Analyzers.Test/SquiggleCop.Baseline.yaml
Add [SquiggleCop](https://github.com/MattKotsenas/SquiggleCop) to baseline the analyzers and their configuration. This intends to prevent accidental changes / regressions to the project, such as #165.
Changes made
- Add `SquiggleCop.Tasks` and wire into the existing `$(PedanticMode)` to validate baselines
- Add `SquiggleCop.Tool` to support ad-hoc baselining / troubleshooting
- Update `CONTRIBUTING.md` with re-baselining procedure
- Update SDK in `global.json` to latest version and disable rollforward to support reproducible build
- Update pipelines to upload SARIF files to aid debugging
> Add SquiggleCop to baseline analyzer settings

- .config/dotnet-tools.json
- build/targets/codeanalysis/CodeAnalysis.targets
- build/targets/codeanalysis/Packages.props
- Update SquiggleCop to the latest version
- Remove the `SetErrorLog` target now that SquiggleCop does so automatically
> Update SquiggleCop and remove ErrorLog property

- build/scripts/Set-SquiggleCopBaseline.ps1
- build/targets/codeanalysis/.globalconfig
- build/targets/codeanalysis/CodeAnalysis.props
- build/targets/codeanalysis/Packages.props
- src/Moq.Analyzers/AsShouldBeUsedOnlyForInterfaceAnalyzer.cs
- src/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- src/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodCodeFix.cs
- src/Moq.Analyzers/Common/ArrayExtensions.cs
- src/Moq.Analyzers/Common/DiagnosticCategory.cs
- src/Moq.Analyzers/Common/DiagnosticExtensions.cs
- src/Moq.Analyzers/Common/DiagnosticIds.cs
- src/Moq.Analyzers/Common/MoqMethodDescriptorBase.cs
- src/Moq.Analyzers/Common/WellKnownTypeNames.cs
- src/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- src/Moq.Analyzers/MoqSetupMethodDescriptor.cs
- src/Moq.Analyzers/NoMethodsInPropertySetupAnalyzer.cs
- src/Moq.Analyzers/NoSealedClassMocksAnalyzer.cs
- src/Moq.Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- src/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
- src/Moq.Analyzers/SquiggleCop.Baseline.yaml
- src/tools/PerfDiff/.editorconfig
- src/tools/PerfDiff/SquiggleCop.Baseline.yaml
- tests/Moq.Analyzers.Benchmarks/Constants.cs
- tests/Moq.Analyzers.Benchmarks/Helpers/CompilationCreator.cs
- tests/Moq.Analyzers.Benchmarks/Helpers/ExportProviderExtensions.cs
- tests/Moq.Analyzers.Benchmarks/SquiggleCop.Baseline.yaml
- tests/Moq.Analyzers.Test/CompositeAnalyzer.cs
- tests/Moq.Analyzers.Test/SquiggleCop.Baseline.yaml
Add [Effective C# Analyzers](https://github.com/rjmurillo/EffectiveCSharp.Analyzers) and set all analyzers to Warning for production code
> Add Effective C# analyzers and update SquiggleCop baselines

- src/Moq.Analyzers/CallbackSignatureShouldMatchMockedMethodAnalyzer.cs
- src/Moq.Analyzers/Common/DiagnosticExtensions.cs
- src/Moq.Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- src/Moq.Analyzers/SetExplicitMockBehaviorAnalyzer.cs
- src/Moq.Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
This is a small, preparatory refactoring change. No behavior differences.
- Add `IOperation` overload to `DiagnosticExtensions` to simplify creating diagnostics
- Align overloads to pass `null` for optional parameters instead of a mix of nulls and empty collections
- Use the most appropriate overload in `.CreateDiagnostic()` calls to simplify code slightly
> Add IOperation to DiagnosticExtensions and clean up overloads

- .editorconfig
#215 added the new `.gitattributes` from .NET, which does git normalization and lets IDEs use the OS default. This avoids a bunch of eol churn because some tools respect `.editorconfig` and some do not. However, I forgot to remove the forced lf in .editorconfig which meant we still got eol churn caused by tools that _did_ respect .editorconfig.
This change removes eol settings from .editorconfig and should (finally) fix eol churn.
> Remove forced lf in .editorconfig

- Directory.Packages.props
Bump `GetPackFromProject` to latest version to pick up fix for race condition in .NET 9 SDK that results in flaky build failures in test projects.
> Bump GetPackFromProject to fix race in .NET 9 SDK

- .github/workflows/main.yml
Currently, the "upload binlogs" step is too far down in the CI pipeline (and also doesn't run if the build fails). Move it up a bit so that the order of log upload mirrors the order of actions and add `success() || failure()` so they are uploaded even during build failures.
> Move "upload binlogs" CI step earlier in pipeline and run even if failed

- src/Analyzers/ConstructorArgumentsShouldMatchAnalyzer.cs
- tests/Moq.Analyzers.Test/ConstructorArgumentsShouldMatchAnalyzerTests.Expressions.cs
When using Moq's expression features for type construction, the Moq1200 analyzer was firing unexpectedly indicating a matching constructor on the type was not found. The `ConstructorArgumentsShouldMatchAnalyzer` was extracting the parameters from the Mock type and comparing them to the parameters of the constructed type as is, including the lambda and the `MockBehavior`.
Example:
```csharp
_ = new Mock<Calculator>(() => new Calculator(), MockBehavior.Loose);
```
> See #234 for more details
This is incorrect for several reasons:
1. The parenthesized lambda is not itself a parameter for the target type, but rather the body
2. The `MockBehavior` would not likely be a parameter on the target type
Correct analysis would be to drop the `MockBehavior` argument as with other configurations of the …
> Remove false positive for Moq1200 when using parameterized lambda

- .github/workflows/release.yml
Updated the workflow configuration for package downloads to target Ubuntu instead of Windows. Windows builds will be removed from the workflow in a future PR.
> Update release.yml to use Ubuntu package instead of Windows

- src/Analyzers/Moq.Analyzers.csproj
- tests/Moq.Analyzers.Test/PackageTests.Baseline#contents.verified.txt
This fixes a regression caused by #290.
`Microsoft.CodeAnalysis.AnalyzerUtilities` is not one of the assemblies provided by the host (i.e. compiler), so we need to include it in our own package.
I'm not sure how to write an automated test for this. Our current tests don't use the NuGet package. Doing something like `dotnet format` in theory should work, but when I tried that it passed even without this change.
This does result in a new package contents baseline, so we can chalk this one up to reviewer error and revisit if we find a better solution.
> Add AnalyzerUtilities to NuGet package

- src/Analyzers/SetupShouldBeUsedOnlyForOverridableMembersAnalyzer.cs
- src/Analyzers/SetupShouldNotIncludeAsyncResultAnalyzer.cs
- src/Analyzers/SquiggleCop.Baseline.yaml
- src/Common/IOperationExtensions.cs
- src/Common/ISymbolExtensions.cs
- src/Common/SemanticModelExtensions.cs
- tests/Moq.Analyzers.Test/SetupShouldBeUsedOnlyForOverridableMembersAnalyzerTests.cs
- tests/Moq.Analyzers.Test/SetupShouldNotIncludeAsyncResultAnalyzerTests.cs
Updates `SetupShouldOnlyBeUsedForOverridableMembersAnalyzer` to use `IOperation` pattern found in explainer #118 
With the IOperation implementation, the symbol specificity is broader on the detected text span, so the test cases were updated to reflect that with a marker move to the beginning and end of the inserted symbol. 
Additional related updates include:
- Adding utility methods for handling code operations and symbol retrieval
- Updated symbol overridability detection logic
Fixes #339
> Refactor SetupShouldOnlyBeUsedForOverridableMembersAnalyzer to IOperation

- .cursor/rules/csharp.mdc
- .github/copilot-instructions.md
- .windsurf/rules/csharp.md
Updates GitHub Copilot, Cursor, and Windsurf rules for working with C#
> Update copilot instructions

- .github/copilot-instructions.md
- .github/instructions/README.md
- .github/instructions/csharp.instructions.md
- .github/instructions/editorconfig.instructions.md
- .github/instructions/generic.instructions.md
- .github/instructions/gitignore.instructions.md
- .github/instructions/json.instructions.md
- .github/instructions/markdown.instructions.md
- .github/instructions/msbuild.instructions.md
- .github/instructions/project.instructions.md
- .github/instructions/shell.instructions.md
- .github/instructions/text.instructions.md
- .github/instructions/xml.instructions.md
- .github/instructions/yaml.instructions.md
Update instruction files to provide clearer guidance for GitHub Copilot when editing C# and project files. Include mandatory instructions, validation checklists, and maintenance notes to ensure comprehensive understanding and adherence to development standards.
> docs: Enhance Copilot instruction files for project files
